version: "3.6"

services:

  postgres:
    image: "postgres:13"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    expose: 
      - 5432   
    volumes:
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/postgresql:/var/lib/postgresql/data:rw

  initdb:
    image: datawhale:tf-2.5
    entrypoint: airflow db init
    depends_on:
        - postgres
    volumes:
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline/dags:/home/datawhale/airflow/dags:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/airflow_logs:/home/datawhale/airflow/logs:rw
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__DAG_CONCURRENCY: 1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 1
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'

  create_user:
    image: datawhale:tf-2.5
    entrypoint: airflow users create -r Admin -u airflow -f datawhale -l datawhale -p airflow -e datawhale@rawthil.com.ar
    depends_on:
        - postgres
        - initdb
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__DAG_CONCURRENCY: 1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 1
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'

  webserver:
    image: datawhale:tf-2.5
    restart: always
    entrypoint: airflow webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /home/datawhale/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
    ports:
        - "8080:8080"
    depends_on:
        - postgres
    volumes:
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline/dags:/home/datawhale/airflow/dags:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/airflow_logs:/home/datawhale/airflow/logs:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline:/home/datawhale/code:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/libs:/home/datawhale/code/libs:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/Datasets:/home/datawhale/datasets:rw
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__DAG_CONCURRENCY: 1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 1
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        

  scheduler:
    image: datawhale:tf-2.5
    restart: always
    entrypoint: airflow scheduler
    healthcheck:
        test: ["CMD-SHELL", "[ -f /home/datawhale/airflow/airflow-scheduler.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
    depends_on:
        - postgres
    volumes:
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline/dags:/home/datawhale/airflow/dags:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/airflow_logs:/home/datawhale/airflow/logs:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline:/home/datawhale/code:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/libs:/home/datawhale/code/libs:rw
        - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/Datasets:/home/datawhale/datasets:rw
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__DAG_CONCURRENCY: 1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 1
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    volumes:
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline/dags:/home/datawhale/airflow/dags:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/airflow_logs:/home/datawhale/airflow/logs:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline:/home/datawhale/code:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/libs:/home/datawhale/code/libs:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/Datasets:/home/datawhale/datasets:rw

  worker:
    image: datawhale:tf-2.5
    command: airflow celery worker
    restart: always
    environment:
      COMMIT_HASH: debug_run_not_tracked
      COMMIT_CLEAN: 'False'
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 4
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    depends_on:
      - redis
    volumes:
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline/dags:/home/datawhale/airflow/dags:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/airflow_logs:/home/datawhale/airflow/logs:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/ml_pipeline:/home/datawhale/code:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/classifier/libs:/home/datawhale/code/libs:rw
      - /home/rawthil/Documents/Work/Okkralabs/MedNotes_classification/Code/untracked/Datasets:/home/datawhale/datasets:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu, compute, utility]
